### ISSUE TITLE
Can I also use the firebase-admin sdk solution for remix deployed on cloudflare pages?

### ISSUE THREAD

**Issue by yelban** [nathanhumphrey/remix-app#1]
Thank you for such a great REMIX AND FIREBASE exploration!
Is it possible to use firebase authentication for remix deployed on cloudflare pages?

![截圖 2022-04-14 下午5 21 27](https://user-images.githubusercontent.com/981381/163355470-6b3bdfa5-5f81-4b4b-a791-d5a11a6d653f.png)

**Comment by nathanhumphrey** [comment]
Theoretically, you should be able to. The only concern I can think of would be accessing the required environment variables (e.g. Firebase service account key). I've never used Cloudflare Pages, but it looks like you can set environment variables via the Cloudflare dashboard and then access them via an `env` property in your code - although, I'm not sure if that only relates to Cloudflare Workers functions or also includes Pages configurations. You will also have to ensure that Cloudflare uses a version of Node >= 14 (the default I see is v12). I'm glad you found the project useful!

**Comment by yelban** [comment]
Thank you for pointing out what works, I will find a way to try out this wonderful tool by adding environment variables to cloudflare
